#!/bin/bash

# basic_shell provides the outer wrapper for the alpha..epsilon shells launched by session-start
#

export shell_id=$1 
cd $HOME
alias exit='echo "Outermost shell. Type [command exit] to really exit"'
bash
while true; do
    (
        bash
        if [[  $? -ne 0 ]]; then
            echo "bash returned  an error" >&2
            read
            exit 1
        fi
        reset
        echo "You are in a basic_shell loop ($1).  Kill $$ to quit"
    )
done

