#!/bin/bash

# bbpy-debug
#
#   Runs a Python script in pudb, using the Bloomberg-specific 'bbpy' interpreter.  If
#   bbpy isn't found, falls back to whatever you have for 'python'.
#
#   IMPORTANT: This script creates symlinks in the current dir to debugger-specific Python
#   code.  You must have write permissions, naturally.  It's also a good idea not to
#   commit these symlinks to source control.
#

pudb_helpers_root=/home/lmatheson4/downloads
export PYTHONPATH=$PWD

# List of symlinks to create.  {symlink_name} {target-relative-to-pudb_helpers_root}
function helpers {
    echo "pudb pudb-254630eec/pudb
pygments pygments-main-8c6c2adfc985/pygments
urwid urwid-59591b8/urwid"
}

#
function errExit {
    echo "ERROR: $@" >&2
    exit 1
}

function makeSymlink {
    local root=$1
    local linkname=$2
    local relsource=$3
    # Make a symlink from $root/$relsource to ./$linkname, if it doesn't exist already.
    [ -h $linkname ] || {  ln -s $root/$relsource $linkname || errExit "Failed creating $linkname to $root/$relsource"; }
    
}

function makeSymlinks {
    while read line; do
        makeSymlink $pudb_helpers_root $line
    done < <(helpers)
}

if [[ -z $sourceMe ]]; then
    # Find bbpy, or fall back to python:
    interp=$(type -P bbpy 2>/dev/null)
    if [[ -z $interp ]]; then
        interp=$(type -P python 2>/dev/null)
        if [[ -z $interp ]]; then
            errExit "Can't find either bbpy or python on the path"
        fi
    fi
    makeSymlinks 

    # Invoke the debugger, forward all params:
    $interp -m pudb.run $@
fi

