#!/bin/bash

source ~/.taskrc/mars-basic-taskrc

buildLibs=false
buildTask=false
quick=false


function errExit {
    echo "ERROR: $@" >&2
    exit 1
}

function parseArgs {
    if [[ -z $1 ]]; then
        echo "Usage: $(basename $0) [-libs] [-tasks] [-q(uick) ]" >&2
        exit 1
    fi
    while [[ ! -z $1 ]]; do
        case $1 in
            -libs)
                buildLibs=true
                ;;
            -tasks)
                buildTask=true
                ;;
            -all)
                buildLibs=true
                buildTask=true
                ;;
            -q)
                quick=true
                ;;
            *)
                errExit "Unknown param: $1"
        esac
        shift
    done
}

if [[ -z $sourceMe ]]; then
    parseArgs $@
    cd $HOME/mars/scripts

    if $quick; then
        args="$args -quick"
    fi
    if $buildLibs; then
        bld -libs -target=m_eqstst $args  || errExit "-libs build failed"
    fi
    if $buildTask; then
        bld -tasks -target=eqstst $args  || errExit "-tasks build failed"
    fi
fi

