#!/bin/bash
# For centos 6.4:

cd /usr/local

sudo yum install curl-devel expat-devel gettext-devel   openssl-devel zlib-devel perl-ExtUtils-MakeMaker || exit 1
if [[ ! -d git/.git ]]; then
	sudo git clone git://git.kernel.org/pub/scm/git/git.git || exit 1
	sudo chmod og+w git -R
fi
cd git
make prefix=/usr/local all || exit 1
sudo make prefix=/usr/local install || exit 1
cd contrib/subtree || exit 1
make prefix=/usr/local || exit 1
sudo make prefix=/usr/local install || exit 1
hash -r
echo "build-git-from-source completed normally."
