#!/bin/bash

function code-edit_f {
    (
        while true; do
            cd $EqststTop
            ~/bin/vim-eqstst
            if [[ $? -ne 0 ]]; then
                echo "vim failed to load." >&2
                read
                exit 1
            fi
            echo "MARSTOP=$MARSTOP"
            echo " You're in an endless code-edit loop. Exit will return to editor.  Kill $$ to really escape the loop."
            bash
        done
    )
}

code-edit_f

