#!/bin/bash
# Launch code-editor loop.  Use -g to use gvim
#
#

[[ "$1" == "-g" ]] && { EDITOR=gvim; shift; }

function fn_map {
    echo "Menu (from ~/bin/code-edit):" >&2
    echo "----------------------------" >&2
    echo "0 must0 cd ~/must/0; $EDITOR"
    echo "1 must1 cd ~/must/1; $EDITOR"
    echo "2 must2 cd ~/must/2; $EDITOR"
    echo " -- -- " 
    echo "y eqstst-0 cd $Mars0/offlines/m_eqstst; $EDITOR"
    echo "x eqstst-2 cd $Mars2/offlines/m_eqstst; $EDITOR"
    echo "n mars-1 cd $Mars1; $EDITOR"
    echo "p mars-3 cd $Mars3; $EDITOR"
    echo " -- -- "
    echo "t test-200k cd ~/test-100k; $EDITOR"
    echo " -- -- " 
    echo "h home cd ~; $EDITOR"
    echo "s shell cd ~; bash"
    echo "q quit exit"
    echo "" 
}

function printMenu {
    fn_map | awk '{print $1 ") " $2}'
}

function getCmd {
    local menuItem="$1"

    fn_map | grep "^${menuItem}" | awk '{$1=$2=""; print $0; }'
}

while true; do
    printMenu
    read -s -n1 
    cmd=$(getCmd "$REPLY")

    echo "You want to run: $cmd" >&2

    eval "$cmd"
done


