#!/bin/bash

function usage {
    echo "$(basename $0) [date|ns|seconds(default)]" >&2
    echo 1
}

[[ $@ == --help ]] && exit $(usage)

[[ -z $1 ]] && output_mode=seconds || output_mode=$1
date --rfc-3339=$output_mode
