#!/bin/bash

function promptDir {
    while true; do 
        echo "Code-edit loop" >&2
        for x in 0 1 2 3; do
            echo "$x) m$x" >&2
        done
        echo "h) home" >&2
        echo "q) quit" >&2
        read -s -n1
        case $REPLY in
            h)
                echo "$HOME"
                return
                ;;
            q) 
                echo "--quit--"
                return
                ;;
            [0-3])
                xpr="echo \"\$Mars${REPLY}/offlines/m_eqstst\""
                export MARSTOP=$(eval "$xpr")
                eval "$xpr"
                return
        esac
    done
}

function eqstst-edit_f {
    (
        while true; do
            xdir=$(promptDir)
            if [[ $xdir == "--quit--" ]]; then
                return
            fi
            cd $xdir || { echo "Error: can't cd to $xdir" >&2; read -p "Press a key to exit"; exit 1; }
            echo "Launching vim with dir=$PWD"
            vim
            if [[ $? -ne 0 ]]; then
                echo "vim failed to load." >&2
                read
                return
            fi
        done
    )
}

if [[ -z $sourceMe ]]; then
    eqstst-edit_f
fi


