#!/bin/bash
# find-recent-files
#
#   Scan files by modified time, e.g.:
#
#     $ find-recent-files -d 3 dir{1,2}   
#         # Scan dir1, dir2 for files modified <= 3 days ago (default is 1 day)
#
#   Automatically suppresses files in dirs named '.git'


xnames=""
while [[ ! -z $1 ]]; do
    case $1 in
        -d)
            days_back=$2
            shift
            ;;
        *)
            xnames="${xnames} $1"
            ;;

    esac
    shift
done

xnames=${xnames:-'*'}

/usr/bin/find ${xnames}  -type f -newermt "${days_back:-1} day ago" -not -iwholename '*.git*'

