#!/bin/bash
# find-git-repos

# Scans tree from current dir looking for git repos, and prints status about each.

function print_git_summary {
    local xdir=$1
    (
        cd $xdir/..
        echo $PWD:
    )
}

for dir in $(find ./ -type d -name '\.git' 2>/dev/null); do
    print_git_summary $dir
done

