#!/bin/bash

# git-find-repos

#  Print all dirs containing ".git" dir as immediate child.  Does not recurse into such dirs.

function xstub {
    echo "[$*]" >&2
}

function findRepos {
    local dir=${1:-.}
    [[ -d ${dir}/.git ]] && { echo "$dir"; return; }  # print cur dir if there's a .git here


    for xdir in $(ls $dir/* -d 2>/dev/null); do
        findRepos "${xdir}"
    done
    
}

findRepos "$@"


