#!/bin/bash

# git-list-untracked-files prints the list of files that show up in the 'untracked' section of 'git status'.
# By default, this lists only files in and under the current tree.  
#
#   Options:
#       
#       -a:  Include all untracked files in the tree, including parent and sibling paths
#

if [[ "$1" == "-a" ]]; then
    git status | tail -n +5 | head -n -1  | cut -c 3-
else
    git ls-files --others --exclude-standard
fi
