#!/bin/bash

# git-wc-inventory
#
# Recursive find of git repos.  Produce an 'inventory' report
# showing wc status, remotes, etc.


die() {
    echo "ERROR: $*" >&2
    exit 1
}

function xstub {
    echo "[$*]" >&2
}

do_inventory() {
    local top_dir="${1:-$PWD}"
    (
        cd $top_dir || die "Can't cd to $top_dir"
        echo -e "do_inventory>>\t$PWD"
        while read gitpath; do
            
            (
                echo
                echo
                cd ${gitpath} || die "Can't cd to ${gitpath}"
                echo -e "wc-found>>>\t${gitpath}\t$PWD"
                git status 2>&1 | sed 's/^/   /'
                git remote -v 2>&1 | sed 's/^/    /'
                git branch -a 2>&1 | sed 's/^/    /'
            )

        done < <( find . -type d -name '.git'  | sed -e 's^/.git$^^' -e 's%^./%%')
    )
}


if [[ -z $sourceMe ]]; then
    do_inventory "$@"    
fi


