#!/bin/bash

uname -a | grep -q WSL2 && {
    [[ -d /mnt/c ]] && rootDir=/mnt/c || rootDir=/c
    winHome="$(cd ${rootDir}; cmd.exe /C 'echo %USERPROFILE%' )"
    # Get rid of non-printable utf16 junk in output of cygpath... but why?
    rcPath=$(${rootDir}/Program\ Files/Git/usr/bin/cygpath.exe -w "${winHome}" | tr -cd '[:print:]')
    ${rootDir}/Program\ Files/Git/bin/bash.exe --rcfile "${rcPath}\\.bash_profile" "$@"
    exit $?
}
/c/Program\ Files/Git/bin/bash.exe "$@"
