#!/bin/bash
#
#
# gopen
#
#

function errExit {
    echo "ERROR: $@" >&2
    exit 1
}

if $CYGWIN; then
    cygstart $@
elif [[ -x /usr/bin/xdg-open ]]; then
    /usr/bin/xdg-open $@
elif [[ -x /usr/bin/open ]]; then
    /usr/bin/open $@
else
    errExit "Unable to resolve open/gopen"
fi

