#!/bin/bash

# Initialize ~/cyghome and ~/cyghome/.cyg-wsl-environ so that the cygwin() function will work from wsl.
set -x

function errExit {
    echo "ERROR: $@" >&2
    exit 1
}
cygdir=$(ls -d
cbash=$( ls ${cygdir}/bin/bash.exe )
if [[ ! -x $cbash ]]; then
    errExit "Can't find cygwin bash ($cbash)"
fi

(
	cd
	ln -sf $cygdir ./cyghome
)

# Find cygwin's HOME dir:
exec 2>/dev/null
exec 2>&1

echo >~/cyghome/.cyg-wsl-environ
for xv in SHELL PATH HOME; do
    exec 2>/dev/null
    tval=$($cbash -lc "printenv $xv")
    exec 2>&1
    echo $xv="\"$tval\"" >> ~/cyghome/.cyg-wsl-environ
done
cat ~/cyghome/.cyg-wsl-environ



