#!/bin/bash

# journal-taskrc
#

function journal {
    if type -a code &>/dev/null; then
        code $HOME/journal/worklog.md
    else
        vim $HOME/journal/worklog.md
    fi
}

alias jrnl='journal'
