#!/bin/bash

function journal-edit {
    (
        while true; do
            cd $HOME/journal
            $EDITOR ./worklog.jrnl
            if [[ $? -ne 0 ]]; then
                echo "$EDITOR returned an error" >&2
                read
                exit 1
            fi
            echo " You're in an endless journal-edit loop. Exit will return to editor.  Kill $$ to really escape the loop."
            bash
        done
    )
}

journal-edit
