#!/bin/bash
# no-screensaver

function errExit {
    echo "ERROR: $1" >&2
    exit 1
}
echo "This program inhibits the screensaver.  It's a hack, because Les hasn't"
echo "found the real cause of the problem."

while true; do
	xdotool mousemove_relative 0 1
	xdotool mousemove_relative 0 -1
	sleep 30
done
