#!/bin/sh

# Add given dir to the PATH, print the result.  By default
# we add the new dir to the start of the PATH, but if $2='after'
# we'll place it at the end.


# Is this dir already on the PATH?:


if [[ ":$PATH:" == *":$1:"* ]]; then
    echo $PATH  # No change needed
else

	# Should we add before or after?
	if [ "$2" = "after" ] ; then
		echo $PATH:$1
	else
		echo $1:$PATH
	fi
fi

