#!/bin/bash

# playnoise {config-name}
# 
# We keep configs in ~/.config/playnoise/conf.d
# Each is a set of sourced params
#
# If no config-name supplied, we use the conf named 'default',
# which may be a symlink.
#
# Use --list to print the config names
#
# Depends only on mpg123

#  tracklist={file/path file/path ...}

pnRoot=$HOME/.config/playnoise
cfgRoot=$pnRoot/conf.d

tracklist=""
cfgname="default"

function errExit {
	echo "ERROR: $@" >&2
	exit 1
}

function parseParams {
	while [[ ! -z $1 ]]; do
		case $1 in
			--list | -L)
				ls -1 $cfgRoot
				exit 0
			;;
			*)
				cfgname=$1
				;;
		esac
		shift
	done
	if [[ ! -f $cfgRoot/$cfgname ]]; then
		errExit "Can't find config $cfgname in $cfgRoot"
	fi
}

function loadConfig {
	local cfgfile="$1"
	source $cfgfile || errExit "Failed sourcing $cfgfile"
}

function checkPrereqs {
	if ! which mpg123 >/dev/null; then
		errExit "mpg123 not found"
	fi

}

function runPlay {
	local tracklist="$1"
	quitRequest=false
	echo "Use spacebar/enter to pause and resume."
	trap 'quitRequest=true' SIGINT
	while ! $quitRequest; do
		mpg123 -C $tracklist
	done
}

if [[ -z $sourceMe ]]; then
	mkdir -p $cfgRoot

	parseParams "$@"

	loadConfig "$cfgRoot/$cfgname"

	checkPrereqs

	runPlay "$tracklist"

fi



	

