#!/bin/bash

# pysh: run an interactive python session with some handy built-ins

PYVER=${PYVER:-2}



if type -a rlwrap &>/dev/null; then
    RLWRAP=$(which rlwrap)
else
    echo "rlwrap is not installed, readline support disabled."
fi

#python${PYVER} -i ~/bin/pysh_core.py "$@"
$RLWRAP python${PYVER} -i ~/bin/pysh_core.py 


