#!/bin/bash

# Start a master session: launch multiple gnome-terminals
#

startXpixel=1309
startYpixel=200
startWidth=60
startHeight=20

commonArgs=--geometry=${startWidth}x${startHeight}+$startXpixel+$startYpixel
# Alpha window is front-and-center:


function launchSingle {
    local name=$1
    case $name in
        alpha )
            gnome-terminal --geometry=120x55+500+500 --window-with-profile=alpha -e "basic_shell $name" &
            sleep 0.5
            ;;
        beta | gamma | delta ) 
            gnome-terminal $commonArgs --window-with-profile=$name -e "basic_shell $name" &
            sleep 0.5
            ;;
        sd61 | sdv61 | ibm9 | sd9 |  sdv9 | sd24 ) 
            gnome-terminal $commonArgs --window-with-profile=$name -e "ssh $name " &
            sleep 0.5
            ;;
        journal-edit )
            gnome-terminal --geometry=120x45+100+100 --window-with-profile=journal -e 'journal-edit' &
            sleep 0.5
            ;;
        code-edit )
            gnome-terminal --geometry=120x45+200+200 --window-with-profile=code -e 'code-edit' &
            sleep 0.5
            ;;
        *)
            echo "Unknown window name $name" >&2
            exit 1
            ;;
    esac

}

if [[ -z $1 ]]; then
    # Default to "all windows":
    for sx in alpha beta sd9 sd24 journal-edit code-edit ; do
        launchSingle $sx
    done
else
    while [[ ! -z $1 ]]; do
        # Just the windows requested on cmd line:
        launchSingle $1
        shift
    done
fi



