#!/usr/bin/expect
eval spawn ssh -Y -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@pigs-green.bacon.illumina.com
#use correct prompt
set prompt ":|#|\\\$"
interact -o -nobuffer -re $prompt return
send "calvin\r"
#interact
