#!/bin/bash
# tagRebuild
#



function errExit {
    echo "ERROR: $@" >&2
    exit 1
}

function stub {
#    echo "STUB: $@" >&2
    echo -n >/dev/null
}


if [[ -z $sourceMe ]]; then
    # We keep the list of dirs to tag in ~/bin/mars-tags-dirs-list.txt
    dirMap=$HOME/bin/mars-tags-dirs-list.txt
    
    cd $HOME/mars
    rm ./tags
    stub "pwd=$PWD"
    
    (
        exec 8< <( grep -v '^#' $dirMap )
        while read -u 8 line; do
            # Append these tags to existing ./tags file:
            [[ -z $line ]] && continue
            stub "Dir: $(ls $line)"
            ctags -a -R $line  || errExit "Failed tagging $line (see $dirMap)"
        done
        exec 8<&-
    )
fi





