#!/bin/bash
# taskrc_new: create a new taskrc in $taskrc_dir using template content


taskrc_dir=${taskrc_dir:-$PWD}

function taskrc_new {
    echo "# taskrc for $PWD"
    echo "# vim: filetype=sh :"
    echo ""
    echo "#  Use taskrc -h for help on built-in taskrc functions."
    echo "#  To provide help for definitions in this file, add #Help tags, e.g.:"
    echo "#    function my_func {"
    echo "     #Help: my_func is my first and only function..."
    echo
}


cd ${taskrc_dir} || errExit "Can't cd to $taskrc_dir"
taskrc_new  > taskrc


