#!/bin/bash
# testshell
#  
#  Launch a shell in a test-oriented temporary HOME dir, for validating
#  stuff in an empty new-user environment
#  
#    Options:
#      -s: [path/to/startup/script]  # This gets appended to .bashrc or .kshrc, so it runs
#               when the test shell starts
#
#      -i: [path/to/init/script]   # This gets invoked just before we start the
#               test shell, so the filesystem can be customized.
#
#      -k:  Use ksh instead of bash
#
#      -- [args passed to shell ] # Everything after -- is passed to the shell
#
# 
function print_profile {
    echo "HOME=$PWD"
    echo "export HOME"
    echo "export TERM=$TERM"
    echo "export TESTSHELL=1"
    echo "export SHELL=$SHELL"
    echo "source \$HOME/${rcfile}" 
}

function print_shrc {
    echo "PATH=/usr/bin:/bin"
    echo "export PATH"
}

function errExit { 
    echo "ERROR: $*" >&2
    exit 1
}

initScript=""
useKshell=false
rcfile=".bashrc"
SHELL="/bin/bash"

if [[ -z $sourceMe ]]; then
    while [[ ! -z $1 ]]; do
        case $1 in
            -s|--start-script) 
                startScript=$(readlink -f $2)
                shift
                ;;
            -i|--init-script)
                initScript=$(readlink -f $2)
                shift
                ;;
            -k|--ksh)
                newShell=/bin/ksh
                useKshell=true
                rcfile=".kshrc"
                SHELL=/bin/ksh
                ;;
            --)
                break;
                ;;
            *)
                errExit "Unknown argument: $1"
                ;;
        esac
        shift
    done
    newHome=$(mktemp -d /tmp/tstsh_XXXXX)
    echo "=================== TEST SHELL ================="
    echo "Temp HOME is ${newHome}"
    echo "================================================"
    cd ${newHome} || errExit 0x102
    print_profile > .profile
    print_shrc > ${rcfile}
    if [[ -f "$startScript" ]]; then
        echo "
        source $startScript" >> ${rcfile}
    fi
    if [[ ! -z $initScript ]]; then
        if [[ -x $initScript ]]; then
            # The caller supplied an init script to run before the shell starts
            $initScript
        else
            errExit "Can't find your initScript or it's not executable [ $initScript ]"
        fi
    fi
    env -i PATH=/usr/bin:/bin HOME=${newHome} $SHELL -l 
    read -p "Test shell exited.  Delete ${newHome}? (y/N)"
    if [[ $REPLY =~ [yY] ]] ; then
        if [[ ! -z ${newHome} ]]; then
            rm -rf ${newHome}
        fi
    fi
fi



# vim: filetype=sh:
