#!/bin/bash
# tmux-main: starting tmux with a canned window set
#
#   Reminders:
#
#     help:   <prefix> ?
#     logging: Use -vvvv for very very verbose logging.  Logs are written to current dir starting tmux as 
#               tmux-client[timestamp].log
#
source ~/bin/tmux-common

session_name=${session_name:-Main}
window_name=${window_name:-M1}

if isTmuxRunning; then
    if  [[ ${session_name} == Main ]] ; then
        echo "ERROR: There's already a tmux session running" >&2
        exit 1
    fi
    echo "Starting secondary session $session:$window_name:"
fi

makeSet_DISPLAY >/dev/null

# Create the session, but don't attach:
echo "tmux  new-session -d -s $session_name -n $window_name" 
tmux  new-session -d -s $session_name -n $window_name  # The ordinary version of this command

if [[ ${session_name} != Main ]]; then
    tmux -2 attach-session -t $session_name 
    exit 0
fi

# Split the window:
tmux split-window -h

# Create a 2nd window:
tmux new-window  -n M3

# Switch to the first window:
tmux last-window


# Now attach the current terminal to the session.
#
#    -d dumps any other terminals on that session.
#    -2 means "assume 256 colors"
tmux -2 attach-session -t $session_name -d 

