#!/bin/bash
# tmux-main: starting tmux with a canned window set
#
#   Reminders:
#
#     help:   <prefix> ?
#     logging: Use -vvvv for very very verbose logging.  Logs are written to current dir starting tmux as 
#               tmux-client[timestamp].log
#
source ~/bin/tmux-common

do_force=false
session_name=A



while [[ ! -z $1 ]]; do
    case $1 in
        --force|-f)
            do_force=true
            ;;
        *)
            echo "ERROR: unknown arg $1" >&2 ; 
            exit 1; 
            ;;
    esac
    shift
done

if isTmuxRunning; then
    if ! $do_force; then
        echo "There's already a tmux session running, use 'tmux attach' or 'tmux-main --force|-f'"
        read -n1 -p "Hit ENTER to exit."
        exit 1
    fi
    session_name=B
    echo "Warning: FORCE-ing a new tmux session as ($session_name)" >&2
fi

makeSet_DISPLAY >/dev/null

# Create the session, but don't attach:
#tmux -vvv new-session -d -s $session_name -n MAIN  # The very-very-verbose version of this command
tmux -vvv new-session -d -s $session_name -n MAIN  # The ordinary version of this command

# Split the _wolf window:
tmux split-window -h

# Create a 2nd _scratch window:
tmux new-window -n _scratch_  

# Switch to the _wolf window:
tmux last-window



# Now attach the current terminal to the session.
#
#    -d dumps any other terminals on that session.
#    -2 means "assume 256 colors"
tmux -2 attach-session -t $session_name -d 
