#!/bin/bash

# tty-dumb:  print the current tty, then enter an endless sleep loop.
# This turns the current terminal into a "dumb" I/O destination for gdb inferior console

function showMsg {
    echo "This terminal is running tty-dumb."
    echo "Start gdb in a 2nd terminal, and then run these commands:"
    echo ""
    echo "  (gdb) tty $(tty)"
    echo "  (gdb) file ./myprog.linux.tsk  # Or whatever"
    echo "  (gdb) run"
    echo ""
    echo "Gdb will direct your program's I/O to this window"
    }

    
showMsg
while true; do
    sleep  1000
done

