#!/bin/bash
# Run vim on files in `git ls-files`.
# If argument(s) are provided, they're treated as egrep filter params,
# e.g.
#    vimgit 'py$|h$' -v
#    ... run egrep, filter-out python and .h files...
#

function do_vimgit {
    if [[ $# == 0 ]]; then
        vim `git ls-files`
    else
        vim $(git ls-files | egrep $@)
    fi
}

if [[ -z $sourceMe ]]; then
    do_vimgit $@
fi

