#!/usr/bin/env bash

function do_vimgit {
    # If there's a .vimgit file in this dir, we source it to generate the 
    # list of files-to-load:
    #stub "pwd=$PWD"
    if [[ -f ./.vimgit ]]; then
        #stub xyz
        # Record the existence of this .vimgit file for administration:
        mkdir -p $LmHome/.taskrc/vimgit-files &>/dev/null
        local lo=$PWD/.vimgit
        local lx=$(echo ${PWD:1} | tr '/' '.')
        ( cd $LmHome/.taskrc/vimgit-files && ln -sf $lo "./$lx.vimgit" )

        $EDITOR $(source ./.vimgit $* ) 
    else
        # Fall-through behavior is provided by canonical:
        $EDITOR $( $LmHome/bin/vimgit-canonical $* )
    fi
}

if [[ -z $sourceMe ]]; then
    do_vimgit $*
fi

