#!/bin/bash
#
# waitdiff [-n seconds] command to test
#    Run command every -n seconds ( default=2.0 ).  When the output changes, exit.
#    Returns: 0 on diff detection, non-zero on error
#

function calcSum {
    local cmd="$@"
    sha1sum <(sh -c "$cmd") | cut -d ' ' -f 1
}

function main {
    local sleep_interval_secs=2
    while [[ -n $1 ]]; do
        case $1 in
            -n)
                sleep_interval_secs=${2:-${sleep_interval_secs}}
                shift 2
                ;;
            *)
                break;
                ;;
        esac
    done
    local cmd="$@"
    local origsum=$(calcSum "$cmd")

    [[ -n $origsum ]] || { false; return; }

    while true; do
        sleep $sleep_interval_secs 
        [[ $origsum == $(calcSum "$cmd") ]] || { true; break; }
    done
}

[[ -z $sourceMe ]] && main $@

